sudo: required
language: java
services:
- docker
jdk:
- openjdk11
notifications:
  email: false
env:
  global:
  - secure: mH9sSynn6qELhJgfFMz5Zff4BexB1alMBgMlGhZqc+6xJ0tJ1VrhZQVpcjoKuBiEkTqHYWYmYTiG/pC65glHkpeiljGCRWKozKzw4o/O7fY70UbMK7TIDhFioHDEzQ1Vn/lx1PH9T7QHMUzt+rj0NX70xSL9Ezx29iSChyMPwId+bFXXAyLUNxzAEQzs6BKy8ufFhCDhsECCeCQQ6u1GdCttxIhgbQlZ/Vo4NzqW3si455bF3vpgHCBt/xtbKlN6Qh04ImS6mt8EFQjo0NFYhCIKxRVFzj26nUcanweQQ7N5ZsvSbvluK5Nw31MbpZiWKyzS1Mf0SkCnTCPz3NkOaArD39PT5lHQin1HicJyF9liK5m3YlvxmNrLQup9nYvu+2jl1/zELUA0vL1lRT+jsirs0kIS8cFWmN9lTG50V3CuX1Kl3vhPDV9ZXpqc08uB0w4yMmlaJeUW09v/3PgjcbNR40Zgj+krnUpkurLgtGjCgke1zuEv/TO+Ij8oUQQeUnsQtwFn1LT6Dy1uBHuGe9E7Aiudqn60xWBFX0NscRU2BARJLlJ0mco+tNM9swktIHepgQz63z6BcIg5v+TsFjX20N+2WWSXI+51HJBXh3ztiD3rluhIPxxMIKMdprU3XeEDeFZO3+BgbQlWHj/jLBw8xUPkPSeRWsIndtu9KTs=
  - secure: GVUg9+X5io4T/HHYsG7O4nDdVjyMBezgauphLWuBkzQrQ/vY8mT7KrwKI4TAZd3ceJ+vR3iHio9eNcBsb2/0kd0Yef2O0IKA/fE/qppVOlNJT2532+wSkKr7Z1U0OJzcZH8v2HJTAf9qQ75TVOS4PF+MZLkGdsEfPX+SJzkdJMlgF7i9Xypt7lF0rmnU/NCD2chCG/Aq7Z6TNQ3ull/9MbDAJC5c4d/8937pY+i+MudAud4dlNpCPmpQoiR4zDH8EnyF40FKTlFM0ykEX6RlsF5A9bobqvpJLvU7WG745SQOmYquyxFk0xzgNCamRyRzLGlupQIiZSFiMEQWhYgaJMeKqKKkkDeRKCiWzMYw1JI3JJdSPiLu4V+6nPOGzP6hheTgbLwlDLD6HGZTXbadHzC6RYIkrzf/9q+npo/F+ik5BcIDjsmd0sgO3IDWw5Z14s5G3oEqR2B1WJ2VcvNyhLQs+PJqOfgTLapNlHc0ZJs8Odhp7aND5MWsKEPTMCYmmPQ4u0nK+tUWPiOVIHe8KZNSkIY2441O/QkykDpx2VCYQ+Ef+C84Wyah2SGWnCMlYE9eOwFgNeERTRctKTa5t274dNyHhKyt40bZ1m9S1azqFwzs/JdNPpA2Qmm1a3Zd6pxtFaEakybAZyUNKGztG54jm8py0LmNn6ehlmqgdDg=
script: ".travis/build_script.sh"
after_success: ".travis/push_script.sh"
