apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: veidemann-db-initializer
build:
  artifacts:
    - image: norsknettarkiv/veidemann-db-initializer
      jib: {}
deploy:
  kustomize:
    paths:
      - 
