apiVersion: "v1"
kind: "crawlJob"
id: "c856d12d-14e0-4554-9bc8-11189b8ab01f"
meta:
  name: "Default"
  description: "The default job definition"
  label:
  - key: "type"
    value: "default"
crawlJob:
  scheduleRef:
    kind: "crawlScheduleConfig"
    id: "5604f0cc-315d-4091-8d6e-1b17a7eb990b"
  limits:
    maxDurationS: 60
  crawlConfigRef:
    kind: "crawlConfig"
    id: "f8609d3f-9bf2-416c-ad50-7774b7d2dd95"
---
apiVersion: "v1"
kind: "crawlJob"
id: "8a260b58-2877-462f-b0b7-b5e4a8dde507"
meta:
  name: "Every day"
  description: "A job running every day"
  label:
  - key: "type"
    value: "default"
crawlJob:
  scheduleRef:
    kind: "crawlScheduleConfig"
    id: "1960663c-4bfa-4002-bc1b-24338bb66aa4"
  limits:
    maxDurationS: 86400
  crawlConfigRef:
    kind: "crawlConfig"
    id: "f8609d3f-9bf2-416c-ad50-7774b7d2dd95"
---
apiVersion: "v1"
kind: "crawlJob"
id: "64ea2951-014a-4c74-b68f-d5f7855dcb04"
meta:
  name: "Work hours"
  description: "A job running every hour between 7 and 15 UTC, Monday through Friday"
  label:
  - key: "type"
    value: "default"
crawlJob:
  scheduleRef:
    kind: "crawlScheduleConfig"
    id: "846cbc1e-540b-460b-bc75-2d2a2d4193c5"
  limits:
    maxDurationS: 86400
  crawlConfigRef:
    kind: "crawlConfig"
    id: "f8609d3f-9bf2-416c-ad50-7774b7d2dd95"
---
apiVersion: "v1"
kind: "crawlJob"
id: "e46863ae-d076-46ca-8be3-8a8ef72e709e"
meta:
  name: "Unscheduled"
  description: "A job which will never trigger. Suitable for manual runs"
  label:
  - key: "type"
    value: "default"
crawlJob:
  limits:
    depth: 10
    maxDurationS: 86400
    maxBytes: 1073741824
  crawlConfigRef:
    kind: "crawlConfig"
    id: "f8609d3f-9bf2-416c-ad50-7774b7d2dd95"
